[build]
publish = "public"
command = "cross-env GATSBY_EXPERIMENTAL_PAGE_BUILD_ON_DATA_CHANGES=true gatsby build --log-pages"

[build.environment]
YARN_VERSION = "1.17.0"
YARN_FLAGS = "--no-ignore-optional"
